## In this notebook We will do Two Case study of Chi-Square which is a Hypthesis test in statistics
- Goodness of fit test
- Test of Indendence

## Case Study - I (Goodness of fit test)

In [1]:
import pandas as pd
from scipy.stats import chisquare

In [2]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
data = pd.read_csv(url)

data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### we will use chi-square goodness of fit to see if the Pclass column is uniformly distributed

In [5]:
# count passenger in each class 
class_counts = data["Pclass"].value_counts().sort_index()
class_counts

Pclass
1    216
2    184
3    491
Name: count, dtype: int64

In [9]:
# Calculated the expected counts assuming a uniform distribution
total_passengers = len(data)
expected_counts = total_passengers/3
expected = [expected_counts]*3
print("Expected passengers counts assuming (Uniform Distribution):\n", expected)

Expected passengers counts assuming (Uniform Distribution):
 [297.0, 297.0, 297.0]

In [12]:
# perform the chi-square goodness of fit test
chi2, p_value = chisquare(class_counts, expected)

print("Chi-Square Statistic: {:.2f}".format(chi2))
print("P-Value: {:.4f}".format(p_value))

Chi-Square Statistic: 191.80
P-Value: 0.0000

In [13]:
# interpret the result
alpha = 0.05
if p_value < alpha :
    print("We reject the null hypothesis. The distribution of passengers among the class is not uniform")
else:
    print("We failed to reject the null hypothesis")

We reject the null hypothesis. The distribution of passengers among the class is not uniform

## Case Study - II(Test of Independence)

In [14]:
from scipy.stats import chi2_contingency

#### We will use chi-square test of Independence to see if the survival rate of passengers is independent of the passenger class

In [15]:
contingency_table = pd.crosstab(data["Survived"], data["Pclass"])
contingency_table

Pclass      1   2    3
Survived
0          80  97  372
1         136  87  119

In [19]:
## Perform the chi-square Test of Independence
chi2, p_value, dof, expected = chi2_contingency(contingency_table)

print("Chi-Square Statistics: {:.2f}".format(chi2))
print("P-Value: {:.4f}".format(p_value))
print("Degree of freedom: ",dof)
print("Expected Frequencies: \n{}".format(expected))

Chi-Square Statistics: 102.89
P-Value: 0.0000
Degree of freedom:  2
Expected Frequencies:
[[133.09090909 113.37373737 302.53535354]
 [ 82.90909091  70.62626263 188.46464646]]

In [ ]:
## Interpret the  result

alpha = 0.05
if p_value < alpha:
    print("We reject the null hypothesis. There is significant association between passenger class and survival rate")
else:
    print("We Faie