## In this notebook we'll learn about Filter-Based method of Feature Selection

In [23]:
import numpy as np
import pandas as pd

data = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQtBXo5cBnDsM2fmfHPm6u72KGUS5FjPHNGMxOfYjA9-CAhmnRpwkIw_rOR3sANJIToiUU__6fbBvig/pub?gid=572763137&single=true&output=csv")

In [24]:
data.head()

,Time,0,1,2,3,4,5,6,7,8,...,581,582,583,584,585,586,587,588,589,Pass/Fail
0,2008-07-19 11:55:00,3030.93,2564.00,2187.7333,1411.1265,1.3602,100.0,97.6133,0.1242,1.5005,...,NaN,0.5005,0.0118,0.0035,2.3630,NaN,NaN,NaN,NaN,-1
1,2008-07-19 12:32:00,3095.78,2465.14,2230.4222,1463.6606,0.8294,100.0,102.3433,0.1247,1.4966,...,208.2045,0.5019,0.0223,0.0055,4.4447,0.0096,0.0201,0.0060,208.2045,-1
2,2008-07-19 13:17:00,2932.61,2559.94,2186.4111,1698.0172,1.5102,100.0,95.4878,0.1241,1.4436,...,82.8602,0.4958,0.0157,0.0039,3.1745,0.0584,0.0484,0.0148,82.8602,1
3,2008-07-19 14:43:00,2988.72,2479.90,2199.0333,909.7926,1.3204,100.0,104.2367,0.1217,1.4882,...,73.8432,0.4990,0.0103,0.0025,2.0544,0.0202,0.0149,0.0044,73.8432,-1
4,2008-07-19 15:22:00,3032.24,2502.87,2233.3667,1326.5200,1.5334,100.0,100.3967,0.1235,1.5031,...,NaN,0.4800,0.4766,0.1045,99.3032,0.0202,0.0149,0.0044,73.8432,-1

In [25]:
data.drop("Time",axis=1,inplace=True)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,581,582,583,584,585,586,587,588,589,Pass/Fail
0,3030.93,2564.00,2187.7333,1411.1265,1.3602,100.0,97.6133,0.1242,1.5005,0.0162,...,NaN,0.5005,0.0118,0.0035,2.3630,NaN,NaN,NaN,NaN,-1
1,3095.78,2465.14,2230.4222,1463.6606,0.8294,100.0,102.3433,0.1247,1.4966,-0.0005,...,208.2045,0.5019,0.0223,0.0055,4.4447,0.0096,0.0201,0.0060,208.2045,-1
2,2932.61,2559.94,2186.4111,1698.0172,1.5102,100.0,95.4878,0.1241,1.4436,0.0041,...,82.8602,0.4958,0.0157,0.0039,3.1745,0.0584,0.0484,0.0148,82.8602,1
3,2988.72,2479.90,2199.0333,909.7926,1.3204,100.0,104.2367,0.1217,1.4882,-0.0124,...,73.8432,0.4990,0.0103,0.0025,2.0544,0.0202,0.0149,0.0044,73.8432,-1
4,3032.24,2502.87,2233.3667,1326.5200,1.5334,100.0,100.3967,0.1235,1.5031,-0.0031,...,NaN,0.4800,0.4766,0.1045,99.3032,0.0202,0.0149,0.0044,73.8432,-1

In [26]:
data.shape

(1567, 591)

In [27]:
data["Pass/Fail"].value_counts()

Pass/Fail
-1    1463
 1     104
Name: count, dtype: int64

In [28]:
data.isnull().sum()

0             6
1             7
2            14
3            14
4            14
             ..
586           1
587           1
588           1
589           1
Pass/Fail     0
Length: 591, dtype: int64

### Remove Duplicate columns

In [29]:
duplicate_cols = data.columns[data.T.duplicated()]

print("Duplicaate Columns: ",len(duplicate_cols))

Duplicaate Columns:  104

In [30]:
data  = data.loc[:,~data.T.duplicated()]
data.shape

(1567, 487)

- We go from 591 to 487 columns

In [31]:
from sklearn.model_selection import train_test_split

X = data.iloc[:,:-1]
y = data.iloc[:,-1]

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

## Filling missing values

In [32]:
from sklearn.impute import SimpleImputer

cols = X_train.columns

imputer = SimpleImputer(strategy="median")
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

## Standardize

In [33]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_trans = scaler.fit_transform(X_train)
X_test_trans = scaler.transform(X_test)

In [34]:
X_train = pd.DataFrame(X_train_trans,columns=cols)
X_test = pd.DataFrame(X_test_trans, columns=cols)

## Baseline Model

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [36]:
y_pred = lr.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Acuracy: ",accuracy)

Acuracy:  0.8821656050955414

## Baseline Model: 88% accuracy at 486 number of columns

## Now Filter-Based Feature Selection

## Variance Threshold
- we had removed duplicate columns already otherwise it would've been first step of filter-based Feature selection

In [37]:
from sklearn.feature_selection import VarianceThreshold
sel = VarianceThreshold(threshold=0.05)

sel.fit(X_train)

print("selected Features: ",sel.get_support().sum())

sel.set_output(transform="pandas")

X_train = sel.transform(X_train)
X_test = sel.transform(X_test)

selected Features:  474

- We go from 486 to 474 number of columns

## Correlation

In [38]:
corr_matrix = X_train.corr().abs()

upper = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape),k=1).astype(bool)
)

to_drop = [ col for col in upper.columns if any(upper[col] > 0.95) ]
print("Columns to remove : ",len(to_drop))

Columns to remove :  189

In [39]:
X_train = X_train.drop(columns=to_drop)
X_test = X_test.drop(columns=to_drop)

print("Train Shape: ",X_train.shape)
print("Test Shape: ",X_test.shape)

Train Shape:  (1253, 285)
Test Shape:  (314, 285)

- we gro from 474 to 285 number of columns

## Anova 
- we can only use it when our features are categorical  and target column is continuous

In [40]:
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import SelectKBest

sel = SelectKBest(f_classif, k=100)   # Best 100 columns

sel.fit(X_train, y_train)

sel.set_output(transform="pandas")

SelectKBest(k=100)

In [41]:
X_train_fs = sel.transform(X_train)
X_test_fs = sel.transform(X_test)

print("Train Shape: ", X_train_fs.shape)
print("Test Shape: ", X_test_fs.shape)

Train Shape:  (1253, 100)
Test Shape:  (314, 100)

- we go from 285 to 100 number of columns

- chi-square is also part of Filter-Based feature selection but we can't use that on this dataset because chi-square requires both dependent and independent variable to be categorical

# Moment of Truth

In [42]:
lr = LogisticRegression(max_iter=1000)

lr.fit(X_train_fs, y_train)

LogisticRegression(max_iter=1000)

In [43]:
y_pred_fs = lr.predict(X_test_fs)
accuracy_fs = accuracy_score(y_test, y_pred_fs)

print("Accuracy After Feature Selection(486 to 100 columns): ",accuracy_fs)

Accuracy After Feature Selection(486 to 100 columns):  0.9012738853503185

## So our accuracy go from 88 to 90 after Feature Selection in which we go from 486 to 100 columns so thats a big win